### ISSUE TITLE
Verbose for Matlab bfopen

### ISSUE THREAD

**Issue by petteriTeikari** [openmicroscopy/bioformats#2497]
This falls under enhancement, but would it be possible to have some sort of verbose flag to the very useful Matlab reader as the command window is now filled with status messages? I removed the `disp()` messages from `bfopen.m` but could not easily find for example the following lines:

```
OMETiffReader initializing "fileName"
Reading IFDs
Populating metadata
```

**Comment by sbesson** [comment]
Hi @petteriTeikari, thanks for your feedback, the lines printed on the command window come from the Bio-Formats logging system. The excessive verbosity you are pointing out has been reported by @carandraug in https://github.com/openmicroscopy/bioformats/issues/2233.

For Bio-Formats 5.1.x, you should be able to reduce this in `bfopen.m` directly by modifying [this line of bfopen](https://github.com/openmicroscopy/bioformats/blob/v5.1.10/components/formats-gpl/matlab/bfopen.m#L111) and setting a higher level than `INFO`, `ERROR` for instance.

In Bio-Formats 5.2.x (to be released next month), the logging system will be further improved with the following changes:
- the default logger level in `bfInitLogging` and `bfopen` will be `WARN` instead of `INFO`
- the logger level will no longer be overriden in `bfopen` if initialized but can be modified using `DebugTools.setRootLevel(level)`
