### ISSUE TITLE
TIFF to TIFF conversion is corrupted 

### ISSUE THREAD

**Issue by felixveysseyre** [openmicroscopy/bioformats#2798]
Hello,

I am using `bfconvert` executable to extract images from a TIFF file:
`bfconvert -bigtiff -series 0 "input.tiff" ".../output.%z.%t.%c.tiff" `

The process run correctly but at the end the TIFF image `output.0.0.0.tiff` seems corrupted:
![capture d ecran 2017-03-22 a 15 54 31](https://cloud.githubusercontent.com/assets/4909259/24204130/dcce8c0e-0f17-11e7-9f24-21ecabc190f5.png)

[Here](https://drive.google.com/file/d/0B-xvT4_QuWKMamhtRkZINnBQWGM/view?usp=sharing) is the data for which I got the issue.

I am using `bfconvert 5.4.0`.

Thanks for your time and your tools !

**Comment by dgault** [comment]
Hi Felix,

I have been testing this morning with the sample file provided and the command line tools from Bio-Formats 5.4.0. So far I have unable to recreate the same 'noise' as you are seeing it.

A couple of basic questions I would have to start:
- Can you confirm that running `bfconvert -version` displays `Version: 5.4.0`
- What operating system were you using?
- What software were you using to display the converted image?
- Would it be possible to upload the converted file with the noise for comparison?

**Comment by felixveysseyre** [comment]
Hello David,

I can confirm I am using latest `bftools` executables:

> Version: 5.4.0
> Build date: 20 March 2017

But the same error was also occurring with `5.3.3`.

I have tested this behavior on both Ubuntu (14.04) and MacOS (10.11).

I am not able to display directly the `output.0.0.0.tiff` file. I tried :
- Ubuntu: Default viewer
- Mac: Default viewer, GIMP
- Windows: Default viewer, GIMP

Do you advise any viewer for MacOS or Ubuntu ?

The `output.0.0.0.tiff` file is later tiled into multiple JPEG files thanks to a C++ executable built on top of ITK and SCIFIO. It corresponds to the image I uploaded for this issue.

Since I was not able to open the `output.0.0.0.tiff`, file I supposed it came from `bfconfert`.

Thanks for your time !

**Comment by felixveysseyre** [comment]
@dgault Do you any news ?

**Comment by dgault** [comment]
Hi Felix,

Firstly apologies for the delayed response, the `output.0.0.0.tiff` would indeed be the file generated from the bfconvert command you were using. A simple way to view this output would be to use the `showinf` command which is available along with bfconvert as part of the Bio-Formats command line tools .

`showinf output.0.0.0.tiff` will read and print the metadata from the output file and an image viewer will open. Due to the filesize this may be quite memory intensive. 

Another option would FIJI (https://fiji.sc/) which comes with Bio-Formats included. Once installed you can read files using `Plugins -> Bio-Formats -> Bio-Formats Importer`

**Comment by sbesson** [comment]
This issue has been addressed and has no further activity. It is therefore being closed. Thank you
for your contributions, they are much appreciated.
